name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Node.js app image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}/node-app:latest .
        docker push ${{ secrets.ECR_REPOSITORY }}/node-app:latest

    - name: Build and push NGINX image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}/nginx:latest -f Dockerfile.nginx .
        docker push ${{ secrets.ECR_REPOSITORY }}/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
